---

- name: NTP client | package
  tags:
    - package
  package:
    name: ntp

- name: NTP client | config
  tags:
    - config
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp

- name: NTP client | service
  tags:
    - service
  service:
    name: ntp
    state: started
    enabled: yes
